name: Deployment

on:
  pull_request:
    types:
      - closed
      
permissions:
  contents: read
  pages: write
  id-token: write
      
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name : Npm install
        run : npm i
      - name : Npm build
        run : npm run build
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

